import { db } from '..'
import { province } from '../schema/province'

export async function provinceSeeder() {
  await db.insert(province).values([
    { name: 'Aceh', code: 'AC' },
    { name: 'Sumatera Utara', code: 'SU' },
    { name: 'Sumatera Barat', code: 'SB' },
    { name: 'Riau', code: 'RI' },
    { name: 'Jambi', code: 'JA' },
    { name: 'Sumatera Selatan', code: 'SS' },
    { name: 'Bengkulu', code: 'BE' },
    { name: 'Lampung', code: 'LA' },
    { name: 'Kepulauan Bangka Belitung', code: 'BB' },
    { name: 'Kepulauan Riau', code: 'KR' },
    { name: 'DKI Jakarta', code: 'JK' },
    { name: 'Jawa Barat', code: 'JB' },
    { name: 'Jawa Tengah', code: 'JT' },
    { name: 'DI Yogyakarta', code: 'YO' },
    { name: 'Jawa Timur', code: 'JI' },
    { name: 'Banten', code: 'BT' },
    { name: 'Bali', code: 'BA' },
    { name: 'Nusa Tenggara Barat', code: 'NB' },
    { name: 'Nusa Tenggara Timur', code: 'NT' },
    { name: 'Kalimantan Barat', code: 'KB' },
    { name: 'Kalimantan Tengah', code: 'KT' },
    { name: 'Kalimantan Selatan', code: 'KS' },
    { name: 'Kalimantan Timur', code: 'KI' },
    { name: 'Kalimantan Utara', code: 'KU' },
    { name: 'Sulawesi Utara', code: 'SA' },
    { name: 'Sulawesi Tengah', code: 'ST' },
    { name: 'Sulawesi Selatan', code: 'SN' },
    { name: 'Sulawesi Tenggara', code: 'SG' },
    { name: 'Gorontalo', code: 'GO' },
    { name: 'Sulawesi Barat', code: 'SR' },
    { name: 'Maluku', code: 'MA' },
    { name: 'Maluku Utara', code: 'MU' },
    { name: 'Papua', code: 'PA' },
    { name: 'Papua Barat', code: 'PB' },
    { name: 'Papua Selatan', code: 'PS' },
    { name: 'Papua Tengah', code: 'PT' },
    { name: 'Papua Pegunungan', code: 'PP' },
  ])
}
